#!/usr/bin/env bash

#---------------------------------------------------#
# Start - Catrina's Post Setup                      #
#---------------------------------------------------#

#---------------------------------------------------#
# Section 0 - Pre Flight                            #
# Section 1 - Login Manager and Tiling Manger Setup #
# Section 2 - Application's and Gaming Install      #
# Section 3 - System Optimsations                   #
# Section 4 - Post Flight                           #
#---------------------------------------------------#

#---------------------------------------------------#
# Section 0 - Pre Flight                            #
#---------------------------------------------------#

echo
echo "Refresh Repos"
echo

sudo pacman -Syu --noconfirm

echo
echo "Done!"
echo

echo
echo "Refresh AUR"
echo

yay -Syu

echo
echo "Done!"
echo

echo
echo "Enable Graphical Target"
echo

sudo systemctl set-default graphical.target

echo
echo "Done!"
echo

#---------------------------------------------------#
# Section 1 - Login Manager and Tiling Manger Setup #
#---------------------------------------------------#

echo
echo "Install Mango Dependacies"
echo

PKGS=(
	'wlr-randr'
	'gnome-keyring'
	'xdg-desktop-portal-gtk'
	'xdg-desktop-portal-wlr'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Install Noctalia and Dependacies"
echo

PKGS=(
	'noctalia'
	'ddcutil'
	'cliphist'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Install Theme Tools"
echo

PKGS=(
	'qt6ct'
	'nwg-look'
	'adw-gtk-theme'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Install Cage and Greetd Regreet"
echo

PKGS=(
	'cage'
	'greetd-regreet'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Configure Greetd Regreet"
echo

sudo mkdir -p /etc/greetd
sudo chown -R greeter:greeter /etc/greetd/
sudo usermod -aG video,render greeter
sudo cp -a /etc/greetd/config.toml /etc/greetd/config.toml.bak
sudo cp -a /etc/greetd/regreet.toml /etc/greetd/regreet.toml.bak
sudo wget -O /etc/greetd/config.toml https://raw.githubusercontent.com/kitkat6464/MyConfigs/refs/heads/mango/sys_cfgs/greetd/config.toml
sudo wget -O /etc/greetd/regreet.toml https://raw.githubusercontent.com/kitkat6464/MyConfigs/refs/heads/mango/sys_cfgs/greetd/regreet.toml
sudo chmod 644 /etc/greetd/config.toml
sudo chmod 644 /etc/greetd/regreet.toml

echo
echo "Done!"
echo

echo
echo "Enable Greetd"
echo

sudo systemctl enable greetd

echo
echo "Done!"
echo

#---------------------------------------------------#
# Section 1 - Login Manager and Tiling Manger Setup #
#---------------------------------------------------#

#---------------------------------------------------#
# Section 2 - Application's and Gaming Install      #
#---------------------------------------------------#

echo
echo "Install Gnome Apps"
echo

PKGS=(
	'vlc'
	'loupe'
	'papers'
	'nautilus'
	'gnome-calendar'
	'gnome-text-editor'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Install Extra Apps"
echo

PKGS=(
	'kitty'
	'bazaar'
	'fastfetch'
	'vlc-plugins-all'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Install Game Apps"
echo

PKGS=(
	'steam'
	'mangohud'
	'gamescope'
	'umu-launcher'
	'lib32-mangohud'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Set Default Configs"
echo

mkdir -p ~/.config/mango
mkdir -p ~/.config/scopebuddy
mkdir -p ~/.config/xdg-desktop-portal
curl -Lo $HOME/.config/mimeapps.list https://raw.githubusercontent.com/kitkat6464/MyConfigs/refs/heads/mango/.config/mimeapps.list
curl -Lo $HOME/.config/mango/config.conf https://raw.githubusercontent.com/kitkat6464/MyConfigs/refs/heads/mango/.config/mango/config.conf
curl -Lo $HOME/.config/scopebuddy/scb.conf https://raw.githubusercontent.com/kitkat6464/MyConfigs/refs/heads/mango/.config/scopebuddy/scb.conf
curl -Lo $HOME/.config/xdg-desktop-portal/mango-portals.conf https://raw.githubusercontent.com/kitkat6464/MyConfigs/refs/heads/mango/.config/xdg-desktop-portal/mango-portals.conf

echo
echo "Done!"
echo

echo
echo "Install ScopeBuddy"
echo

sudo wget -O /usr/local/bin/scopebuddy https://raw.githubusercontent.com/OpenGamingCollective/ScopeBuddy/refs/tags/1.5.0/bin/scopebuddy
sudo chmod +x /usr/local/bin/scopebuddy
sudo ln -s scopebuddy /usr/local/bin/scb

echo
echo "Done!"
echo

#---------------------------------------------------#
# Section 2 - Application's and Gaming Install      #
#---------------------------------------------------#

#---------------------------------------------------#
# Section 3 - System Optimsations                   #
#---------------------------------------------------#

echo
echo "Install Optimsation Tools"
echo

PKGS=(
	'scx-tools'
	'scx-scheds'
	'zram-generator'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Apply Optimsations"
echo

sudo mkdir /etc/systemd/system.conf.d
sudo mkdir /etc/systemd/user.conf.d
sudo wget -O /etc/sysctl.d/70-aleph-settings.conf https://raw.githubusercontent.com/kitkat6464/MyConfigs/refs/heads/mango/sys_cfgs/sysctl.d/70-aleph-settings.conf
sudo wget -O /etc/sysctl.d/99-splitlock.conf https://raw.githubusercontent.com/kitkat6464/MyConfigs/refs/heads/mango/sys_cfgs/sysctl.d/99-splitlock.conf
sudo wget -O /etc/systemd/zram-generator.conf https://raw.githubusercontent.com/kitkat6464/MyConfigs/refs/heads/mango/sys_cfgs/systemd/zram-generator.conf
sudo wget -O /etc/udev/rules.d/30-zram.rules https://raw.githubusercontent.com/kitkat6464/MyConfigs/refs/heads/mango/sys_cfgs/rules.d/30-zram.rules
sudo wget -O /etc/scx_loader.toml https://raw.githubusercontent.com/kitkat6464/MyConfigs/refs/heads/mango/sys_cfgs/scx_loader/scx_loader.toml
sudo wget -O /etc/security/limits.conf https://raw.githubusercontent.com/kitkat6464/MyConfigs/refs/heads/mango/sys_cfgs/security/limits.conf
sudo wget -O /etc/systemd/system.conf.d/10-limits.conf https://raw.githubusercontent.com/kitkat6464/MyConfigs/refs/heads/mango/sys_cfgs/systemd/system/10-limits.conf
sudo wget -O /etc/systemd/user.conf.d/10-limits.conf https://raw.githubusercontent.com/kitkat6464/MyConfigs/refs/heads/mango/sys_cfgs/systemd/user/10-limits.conf
sudo wget -O /etc/systemd/system.conf.d/00-timeout.conf https://raw.githubusercontent.com/kitkat6464/MyConfigs/refs/heads/mango/sys_cfgs/systemd/00-timeout.conf
sudo wget -O /etc/systemd/user.conf.d/00-timeout.conf https://raw.githubusercontent.com/kitkat6464/MyConfigs/refs/heads/mango/sys_cfgs/systemd/00-timeout.conf
sudo wget -O /usr/lib/modules-load.d/ntsync.conf https://raw.githubusercontent.com/kitkat6464/MyConfigs/refs/heads/mango/sys_cfgs/modules-load.d/ntsync.conf
sudo wget -O /usr/lib/udev/rules.d/99-ntsync.rules https://raw.githubusercontent.com/kitkat6464/MyConfigs/refs/heads/mango/sys_cfgs/rules.d/99-ntsync.rules
sudo sysctl --system
sudo systemctl daemon-reload
sudo systemctl start /dev/zram0
sudo systemctl enable --now scx_loader.service
sudo systemctl restart scx_loader.service

echo
echo "Done!"
echo

#---------------------------------------------------#
# Section 3 - System Optimsations                   #
#---------------------------------------------------#

#---------------------------------------------------#
# Section 4 - Post Flight                           #
#---------------------------------------------------#

echo
echo "Refresh Repos Again"
echo

sudo pacman -Syu --noconfirm

echo
echo "Done!"
echo

echo
echo "Refresh AUR Again"
echo

yay -Syu

echo
echo "Done!"
echo

#---------------------------------------------------#
# End - Catrina's Post Setup                        #
#---------------------------------------------------#
