#!/usr/bin/env bash

#---------------------------------------------------#
# Start - Catrina's Post Setup                      #
#---------------------------------------------------#

#---------------------------------------------------#
# Section 0 - Pre Flight                            #
# Section 1 - Noctalia Greeter Setup                #
# Section 2 - MangoWM Setup                         #
# Section 3 - Noctalia Shell Setup                  #
# Section 4 - Core Apps Setup                       #
# Section 5 - Custom Config Setup                   #
# Section 6 - Post Flight                           #
#---------------------------------------------------#

#---------------------------------------------------#
# Section 0 - Pre Flight                            #
#---------------------------------------------------#

echo
echo "Refreshing Repos"
echo

sudo pacman -Syu --noconfirm

echo
echo "Done!"
echo

echo
echo "Enabling Graphical Target"
echo

sudo systemctl set-default graphical.target

echo
echo "Done!"
echo

#---------------------------------------------------#
# Section 1 - Noctalia Greeter Setup                #
#---------------------------------------------------#

echo
echo "Installing Noctalia Greeter"
echo

sudo pacman -S noctalia-greeter --noconfirm

echo
echo "Done!"
echo

echo
echo "Configuring Noctalia Greeter"
echo

sudo mkdir -p /etc/greetd
sudo chown -R greeter:greeter /etc/greetd/
sudo usermod -aG video,render greeter
sudo cp -a /etc/greetd/config.toml /etc/greetd/config.toml.bak
sudo wget -O /etc/greetd/config.toml https://raw.githubusercontent.com/kitkat6464/MyConfigs/refs/heads/mango/sys_cfgs/greetd/config.toml
sudo chmod 644 /etc/greetd/config.toml

echo
echo "Done!"
echo

echo
echo "Enabling Noctalia Greeter"
echo

sudo systemctl enable greetd

echo
echo "Done!"
echo

#---------------------------------------------------#
# Section 2 - MangoWM Setup                         #
#---------------------------------------------------#

echo
echo "Installing Mango and Dependencies"
echo

PKGS=(
	'mangowm'
	'wlr-randr'
	'gnome-keyring'
	'xdg-desktop-portal-gtk'
	'xdg-desktop-portal-wlr'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

#---------------------------------------------------#
# Section 3 - Noctalia Shell Setup                  #
#---------------------------------------------------#

echo
echo "Installing Noctalia and Dependencies"
echo

PKGS=(
	'noctalia'
	'ddcutil'
	'cliphist'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Installing Theming Tools"
echo

PKGS=(
	'qt6ct'
	'nwg-look'
	'adw-gtk-theme'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

#---------------------------------------------------#
# Section 4 - Core Apps Setup                       #
#---------------------------------------------------#

echo
echo "Installing Gnome Core Apps"
echo

PKGS=(
	'loupe'
	'papers'
	'showtime'
	'decibels'
	'nautilus'
	'gnome-logs'
	'gnome-calendar'
	'gnome-text-editor'
	'gnome-disk-utility'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Installing Additional Apps"
echo

PKGS=(
	'kitty'
	'bazaar'
)

for PKG in "${PKGS[@]}"; do
	echo "INSTALLING: ${PKG}"
	sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

echo
echo "Installing ScopeBuddy"
echo

sudo wget -O /usr/local/bin/scopebuddy https://raw.githubusercontent.com/OpenGamingCollective/ScopeBuddy/refs/tags/1.5.0/bin/scopebuddy
sudo chmod +x /usr/local/bin/scopebuddy
sudo ln -s scopebuddy /usr/local/bin/scb

echo
echo "Done!"
echo

#---------------------------------------------------#
# Section 5 - Custom Config Setup                   #
#---------------------------------------------------#

echo
echo "Configuring Custom Configs"
echo

mkdir -p ~/.config/mango
mkdir -p ~/.config/fastfetch
mkdir -p ~/.config/scopebuddy
mkdir -p ~/.local/state/noctalia
mkdir -p ~/.config/xdg-desktop-portal
curl -Lo $HOME/.config/mimeapps.list https://raw.githubusercontent.com/kitkat6464/MyConfigs/refs/heads/mango/.config/mimeapps.list
curl -Lo $HOME/.config/mango/config.conf https://raw.githubusercontent.com/kitkat6464/MyConfigs/refs/heads/mango/.config/mango/config.conf
curl -Lo $HOME/.config/fastfetch/config.jsonc https://raw.githubusercontent.com/kitkat6464/MyConfigs/refs/heads/mango/.config/fastfetch/config.jsonc
curl -Lo $HOME/.config/fastfetch/cute-takopii-anime-sticker.png https://raw.githubusercontent.com/kitkat6464/MyConfigs/refs/heads/mango/.config/fastfetch/cute-takopii-anime-sticker.png
curl -Lo $HOME/.config/scopebuddy/scb.conf https://raw.githubusercontent.com/kitkat6464/MyConfigs/refs/heads/mango/.config/scopebuddy/scb.conf
curl -Lo $HOME/.local/state/noctalia/settings.toml https://raw.githubusercontent.com/kitkat6464/MyConfigs/refs/heads/mango/.local/state/noctalia/settings.toml
curl -Lo $HOME/.config/xdg-desktop-portal/mango-portals.conf https://raw.githubusercontent.com/kitkat6464/MyConfigs/refs/heads/mango/.config/xdg-desktop-portal/mango-portals.conf

echo
echo "Done!"
echo

#---------------------------------------------------#
# Section 6 - Post Flight                           #
#---------------------------------------------------#

echo
echo "Refreshing Repos Again"
echo

sudo pacman -Syu --noconfirm

echo
echo "Done!"
echo

#---------------------------------------------------#
# End - Catrina's Post Setup                        #
#---------------------------------------------------#
