[bar.default]
background_opacity = 0.4999999888241291
capsule = true
center = [ "media", "weather", "clock", "audio_visualizer" ]
end = [ "group:g1", "group:g2", "tray", "notifications", "volume", "control-center" ]
shadow = false
start = [ "privacy", "workspaces", "active_window" ]
widget_spacing = 8

    [bar.default.dead_zone.actions]
    back = "none"
    forward = "none"
    left = "none"
    middle = "none"
    right = "none"
    scroll_down = "none"
    scroll_left = "none"
    scroll_right = "none"
    scroll_up = "none"

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "cpu-mon", "cpu-temp", "ram-used" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g2"
    members = [ "gpu-mon", "gpu-temp", "vram-used" ]
    opacity = 1.0
    padding = 6.0

[calendar]
enabled = true

[control_center.calendar]
show_events_card = false
show_week_numbers = true

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "power_profile"

[[control_center.shortcuts]]
type = "wallpaper"

[[control_center.shortcuts]]
type = "clipboard"

[desktop_widgets]
schema_version = 2
widget_order = [
    "desktop-widget-0000000000000001",
    "desktop-widget-0000000000000002",
    "desktop-widget-0000000000000003",
    "desktop-widget-0000000000000004",
    "desktop-widget-0000000000000005",
    "desktop-widget-0000000000000007",
    "desktop-widget-0000000000000008",
    "desktop-widget-0000000000000009"
]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 128.0
    box_width = 272.0
    cx = 288.0
    cy = 124.0
    output = "DP-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background = false
        clock_style = "digital"
        color = "on_surface"
        shadow = true

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 48.0
    box_width = 384.0
    cx = 224.0
    cy = 1028.0
    output = "DP-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        background = false
        bands = 32
        color_1 = "error"
        color_2 = "error"
        show_when_idle = true

    [desktop_widgets.widget.desktop-widget-0000000000000003]
    box_height = 48.0
    box_width = 384.0
    cx = 1696.0
    cy = 1028.0
    output = "DP-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000003.settings]
        background = false
        bands = 32
        color_1 = "error"
        color_2 = "error"
        show_when_idle = true

    [desktop_widgets.widget.desktop-widget-0000000000000004]
    box_height = 192.0
    box_width = 192.0
    cx = 1296.0
    cy = 652.0
    output = "DP-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "fancy_audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000004.settings]
        background = false
        primary_color = "error"
        secondary_color = "error"
        visualization_mode = "wave_rings"

    [desktop_widgets.widget.desktop-widget-0000000000000005]
    box_height = 128.0
    box_width = 256.0
    cx = 427.0
    cy = 204.0
    output = "DP-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "weather"

        [desktop_widgets.widget.desktop-widget-0000000000000005.settings]
        background = false
        color = "on_surface"
        shadow = true
        show_forecast = false

    [desktop_widgets.widget.desktop-widget-0000000000000007]
    box_height = 192.0
    box_width = 192.0
    cx = 896.0
    cy = 476.0
    output = "DP-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "fancy_audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000007.settings]
        background = false
        primary_color = "error"
        secondary_color = "error"
        visualization_mode = "wave_rings"

    [desktop_widgets.widget.desktop-widget-0000000000000008]
    box_height = 192.0
    box_width = 192.0
    cx = 1664.0
    cy = 220.0
    output = "DP-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "fancy_audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000008.settings]
        background = false
        primary_color = "error"
        secondary_color = "error"
        visualization_mode = "wave_rings"

    [desktop_widgets.widget.desktop-widget-0000000000000009]
    box_height = 0.0
    box_width = 0.0
    cx = 392.0
    cy = 406.0
    output = "DP-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "media_player"

        [desktop_widgets.widget.desktop-widget-0000000000000009.settings]
        background = true
        background_color = "surface"
        background_opacity = 0.80000000000000004
        background_padding = 10
        background_radius = 12
        color = "on_surface"
        font_family = ""
        hide_when_no_media = true
        layout = "horizontal"
        shadow = true

[dock]
background_opacity = 0.4999999888241291
enabled = true
icon_size = 44
launcher_position = "start"
pinned = [
    "org.gnome.Nautilus",
    "firefox",
    "kitty",
    "com.spotify.Client",
    "steam",
    "net.lutris.Lutris",
    "io.github.kolunmi.Bazaar"
]
reserve_space = false
shadow = false
show_dots = true
smart_auto_hide = true

[hot_corners]
enabled = true

    [hot_corners.top_left]
    action = "window_switcher"

    [hot_corners.top_right]
    action = "control_center"

[location]
auto_locate = true

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@DP-2",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000003",
    "lockscreen-widget-0000000000000004",
    "lockscreen-widget-0000000000000006",
    "lockscreen-widget-0000000000000007",
    "lockscreen-widget-0000000000000009",
    "lockscreen-widget-000000000000000a"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 748.0
    output = "DP-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 48.0
    box_width = 448.0
    cx = 224.0
    cy = 1028.0
    output = "DP-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        bands = 32
        color_1 = "error"
        color_2 = "error"
        show_when_idle = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 48.0
    box_width = 448.0
    cx = 1696.0
    cy = 1028.0
    output = "DP-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background = false
        bands = 32
        color_1 = "error"
        color_2 = "error"
        show_when_idle = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 192.0
    box_width = 192.0
    cx = 960.0
    cy = 540.0
    output = "DP-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "fancy_audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        background = false
        fade_when_idle = true
        primary_color = "error"
        secondary_color = "error"
        visualization_mode = "wave_rings"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000004]
    box_height = 128.0
    box_width = 256.0
    cx = 960.0
    cy = 252.0
    output = "DP-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000004.settings]
        background = false
        color = "on_surface"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000006]
    box_height = 192.0
    box_width = 192.0
    cx = 224.0
    cy = 828.0
    output = "DP-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "fancy_audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000006.settings]
        background = false
        fade_when_idle = true
        primary_color = "error"
        secondary_color = "error"
        visualization_mode = "wave_rings"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000007]
    box_height = 192.0
    box_width = 192.0
    cx = 1696.0
    cy = 828.0
    output = "DP-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "fancy_audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000007.settings]
        background = false
        fade_when_idle = true
        primary_color = "error"
        secondary_color = "error"
        visualization_mode = "wave_rings"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000009]
    box_height = 128.0
    box_width = 256.0
    cx = 976.0
    cy = 348.0
    output = "DP-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "weather"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000009.settings]
        background = false
        color = "on_surface"
        show_forecast = false

    [lockscreen_widgets.widget.lockscreen-widget-000000000000000a]
    box_height = 0.0
    box_width = 0.0
    cx = 960.0
    cy = 918.0
    output = "DP-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "media_player"

        [lockscreen_widgets.widget.lockscreen-widget-000000000000000a.settings]
        hide_when_no_media = true

[notification]
background_opacity = 0.4999999888241291

[osd]
background_opacity = 0.4999999888241291

[plugins]
auto_update = "official"

[shell]
avatar_path = "/home/catrina/Pictures/PFPs/pfp1.png"
password_style = "random"
polkit_agent = true
screen_time_enabled = true
settings_show_advanced = false
settings_window_translucent = true

    [shell.greeter_sync]
    auto_sync = true

    [shell.launcher]
    app_grid = true
    categories = false
    sort_by_usage = false

        [shell.launcher.providers.emoji]
        global = true

        [shell.launcher.providers.session]
        global = true

        [shell.launcher.providers.wallpaper]
        global = true

        [shell.launcher.providers.windows]
        global = true

    [shell.panel]
    clipboard_placement = "attached"
    list_item_background = true
    polkit_placement = "attached"
    session_position = "center"
    shadow = false
    transparency_mode = "soft"

    [shell.screen_corners]
    enabled = true

    [shell.screenshot]
    confirm_region = true
    directory = "/home/catrina/Pictures/Screenshots"

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 3.0
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 3.0
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 3.0
    enabled = true
    label = "Hard Reboot"
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    command = "systemctl soft-reboot"
    countdown_seconds = 3.0
    enabled = true
    label = "Soft Reboot"
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 3.0
    enabled = true
    shortcut = "5"
    variant = "destructive"

[theme]
builtin = "Nord"

    [theme.templates]
    builtin_ids = [
        "alacritty",
        "btop",
        "cava",
        "emacs",
        "foot",
        "gtk3",
        "gtk4",
        "ghostty",
        "helix",
        "hyprland",
        "kcolorscheme",
        "kitty",
        "labwc",
        "mango",
        "niri",
        "qt",
        "scroll",
        "starship",
        "sway",
        "umbriel",
        "wezterm"
    ]
    community_ids = [ "pywalfox-beta4" ]

[wallpaper]
directory = "/home/catrina/Pictures/Wallpapers"
transition_on_startup = true

    [wallpaper.default]
    path = "/home/catrina/Pictures/Wallpapers/wallhaven-jxlp8q_1920x1080.png"

    [wallpaper.last]
    path = "/home/catrina/Pictures/Wallpapers/wallhaven-jxlp8q_1920x1080.png"

    [wallpaper.monitors.DP-2]
    path = "/home/catrina/Pictures/Wallpapers/wallhaven-jxlp8q_1920x1080.png"

[widget.active_window]
display = "text_only"
title_scroll = "on_hover"

[widget.audio_visualizer]
show_when_idle = true

[widget.cpu-mon]
type = "sysmon"
visualization = "none"

[widget.cpu-temp]
stat = "cpu_temp"
type = "sysmon"
visualization = "none"

[widget.gpu-mon]
stat = "gpu_usage"
type = "sysmon"
visualization = "none"

[widget.gpu-temp]
stat = "gpu_temp"
type = "sysmon"
visualization = "none"

[widget.media]
artist_first = true
show_progress = true
title_scroll = "on_hover"

[widget.ram-used]
stat = "ram_used"
type = "sysmon"
visualization = "none"

[widget.tray]
drawer = true

[widget.volume]
show_label = false

[widget.vram-used]
stat = "gpu_vram_used"
type = "sysmon"
visualization = "none"

[widget.weather]
show_condition = false
